development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: feely_app
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: feely_app
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: feely_app
  pool: 5
  timeout: 5000
